name: Build and release lib

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Vulkan-Headers
        run: |
          git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git external/Vulkan-Headers
      - name: Build .so
        run: |
          gcc -shared -fPIC -DVKGPGPU_BUILD -Iexternal/Vulkan-Headers/include -o libvkgpgpu.so ./*/*.c

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: libvkgpgpu-linux
          path: |
            libvkgpgpu.so
            include/vkgpgpu.h

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Vulkan-Headers
        run: |
          git clone --depth 1 https://github.com/KhronosGroup/Vulkan-Headers.git external/Vulkan-Headers

      - name: Build DLL
        shell: bash
        run: |
          gcc -shared -Iexternal/Vulkan-Headers/include -o vkgpgpu.dll ./*/*.c -Wl,--out-implib,libmylib.a

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: vkgpgpu-windows
          path: | 
            vkgpgpu.dll
            libvkgpgpu.a
            include/vkgpgpu.h

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: true 
          files: |
            artifacts/libvkgpgpu-linux/libvkgpgpu.so
            artifacts/libvkgpgpu-linux/vkgpgpu.h
            artifacts/vkgpgpu-windows/vkgpgpu.dll
            artifacts/vkgpgpu-windows/libvkgpgpu.a
